version: '3.0'

services:
  api:
    build: ./
    restart: 'always'
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_USER=root
      - MYSQL_DB_NAME=blogs-api
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - JWT_SECRET=secretJWT
      - MYSQL_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 10s
      retries: 5
  db:
    container_name: api_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  default:
    name: blogs_api_net